(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'destinations'"
p3
sS'layer'
p4
S'/home/cmps-107/lib/web2py/applications/TRVLR/controllers/destinations.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\nimport json\n\n# try something like\ndef index():\n    return dict(destinations="TODO insert list of itineraries")\n\ndef get_itineraries():\n    """\n    Return all itineraries matching a place_id\n    """\n    place_id = request.vars[\'place_id\']\n    if place_id is None:\n        return HTTP(400)\n    else:\n        itineraries = db(db.destinations.place_id==place_id,\n                         db.destinations.id == db.itineraries.destination).select(db.itineraries.ALL).as_list()\n        # if request.args[0] and request.args[0] == \'json\':\n        return json.dumps(dict(itineraries=itineraries))\n\nresponse._vars=response._caller(get_itineraries)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/cmps-107/lib/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/cmps-107/lib/web2py/applications/TRVLR/controllers/destinations.py", line 21, in <module>\n  File "/home/cmps-107/lib/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/cmps-107/lib/web2py/applications/TRVLR/controllers/destinations.py", line 16, in get_itineraries\n    itineraries = db(db.destinations.place_id==place_id,\n  File "/home/cmps-107/lib/web2py/gluon/packages/dal/pydal/base.py", line 921, in __getattr__\n    return BasicStorage.__getattribute__(self, key)\nAttributeError: \'DAL\' object has no attribute \'destinations\'\n'
p11
s.